### ISSUE TITLE
IPython.utils.traitlets.TraitError when building container

### ISSUE THREAD

**Issue by cswarth** [SimonBiggs/docker-jupyter#1]
I'm mystified - when I try to build  this image I get an error.  Anyone else see this?  It might be that I'm stuck with an ancient version of docker...

```
$ docker -v
Docker version 1.4.1, build 5bc2ff8
$ docker info
Containers: 434
Images: 1588
Storage Driver: aufs
 Root Dir: /loc/var/lib/docker/aufs
 Dirs: 2514
Execution Driver: native-0.2
Kernel Version: 3.13.0-39-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 12
Total Memory: 47.16 GiB
Name: exmar
ID: IAU6:QBRX:OABV:HFVL:B6JT:EN62:R26U:BCOM:XVQT:XIHN:MXGS:X6TO
WARNING: No swap limit support
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 386189
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 386189
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

```

```
$ docker run --rm -p 8000:8000 simonbiggs/jupyter
[...lots of output...]
3da2b5cfd019: Download complete 
2a700d8b6fe0: Download complete 
95e2776e4827: Download complete 
6cb14c875598: Download complete 
9c478c726d76: Download complete 
80872d0bce6b: Download complete 
61fa7318b16d: Download complete 
Status: Downloaded newer image for simonbiggs/jupyter:latest
Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub", line 4, in <module>
    main()
  File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1031, in launch_instance
    self = cls.instance(argv=argv)
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/configurable.py", line 337, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/application.py", line 234, in __init__
    SingletonConfigurable.__init__(self, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/config/configurable.py", line 86, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py", line 579, in __init__
    setattr(self, key, value)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py", line 444, in __set__
    new_value = self._validate(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py", line 465, in _validate
    value = self.validate(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py", line 1543, in validate
    value = super(List, self).validate(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py", line 1454, in validate
    value = super(Container, self).validate(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py", line 979, in validate
    self.error(obj, value)
  File "/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py", line 812, in error
    raise TraitError(e)
IPython.utils.traitlets.TraitError: The 'argv' trait of a JupyterHub instance must be a list, but a value of class 'NoneType' (i.e. None) was specified.
```

**Comment by SimonBiggs** [comment]
Sorry, I have not been keeping this project up to date at all. It is likely broken.
